if (!window.translations) {
    window.translations = {};
}

window.translations = {
    it: {
        // Core Navbar
        nav_home: "Home",
        nav_languages: "Lingue",
        nav_about_me: "Chi sono",
        nav_login: "Accedi",
        nav_logout: "Esci",
        nav_welcome: "Ciao, ",
        
        // Hero Section
        hero_title: "Impara la tua lingua <br><span>preferita</span> online",
        hero_subtitle: "Una piattaforma eco-interattiva per lo studio delle lingue straniere.",
        btn_choose: "Scegli una lingua",
        
        // Info / About
        about_title: "Dietro le quinte del mondo della linguistica.",
        about_text1: "Il progetto è stato creato da volontari per una comoda immersion nella cultura di diversi paesi.",
        about_subtitle: "Come funziona?",
        about_text2: "Scegli la scheda della lingua che ti interessa, accedi, ottieni l'accesso ai materiali interattivi e impara le parole con divertenti animazioni di transizione.",
        placeholder_map: "Mappa del mondo linguistico",
        
        // Language Grid
        lang_title: "Le nostre direzioni popolari",
        back_btn: "Torna alle lingue",
        
        // Language Cards
        card_zh: "Cinese",
        card_es: "Spagnolo",
        card_en: "Inglese",
        card_it: "Italiano",
        card_ru: "Russo",
        card_ar: "Arabo",
        card_uk: "Ucraino",
        card_pt: "Portoghese",
        card_de: "Tedesco",
        
        // Auth Flow
        auth_title: "Accedi / Registrazione",
        auth_login_label: "Login:",
        auth_pass_label: "Password:",
        auth_placeholder_user: "Crea o inserisci il tuo login",
        auth_placeholder_pass: "Inserisci la password",
        auth_btn: "Continua",
        auth_success_reg: "Registrazione riuscita! Benvenuto, ",
        auth_success_login: "Bentornato, ",
        auth_error_pass: "Password errata!",
        
        // Descriptions
        desc_zh: "Benvenuti nella pagina di studio del cinese. È una delle lingue più antiche e diffuse al mondo, basata su un sistema tonale e sulla scrittura geroglifica.",
        desc_es: "¡Hola! Lo spagnolo è la seconda lingua madre più parlata al mondo. È incredibilmente emotivo, sonoro e relativamente facile da imparare per i principianti.",
        desc_en: "Welcome! L'inglese è la lingua principale della comunicazione internazionale, degli affari, della scienza e della tecnologia.",
        desc_it: "Benvenuti! L'italiano è la lingua della grande cultura, del Rinascimento, dell'opera e della cucina. Quasi tutti i termini musicali nel mondo hanno radici italiane.",
        desc_ru: "Benvenuti! Il russo è una delle lingue più grandi del mondo, famosa per la sua ricca letteratura, la grammatica complessa e l'abbondanza di mezzi espressivi.",
        desc_ar: "Ahlan wa sahlan! La lingua araba si scrive da destra a sinistra e ha un sistema di radici unico per la costruzione delle parole.",
        desc_uk: "Benvenuti! La lingua ucraina è ufficialmente riconosciuta come una delle più melodiose al mondo grazie all'alternanza unica di suoni vocalici e consonantici.",
        desc_pt: "Olá! Il portoghese ha dato al mondo la cultura del fado, della samba e della capoeira. Si parla non solo in Portogallo, ma anche nel grande e soleggiato Brasile.",
        desc_de: "Guten Tag! Il tedesco è la lingua di Kant, Goethe ed Einstein. È noto per le sue parole composte lunghe e l'ordine rigoroso delle parole.",

        // Features (home.js)
        home_features_title: "I Nostri Vantaggi Esclusivi",
        feat_1_title: "Metodo Visivo e Immersione Totale",
        feat_1_text: "Una metodologia d'avanguardia basata sull'associazione immediata tra concetti nativi e immagini ad alta definizione. Questo elimina la necessità di traduzioni mentali intermedie, accelerando lo sviluppo del pensiero intuitivo direttamente nella lingua straniera scelta attraverso percorsi visivi ottimizzati.",
        feat_2_title: "Progressione Accademica Graduale",
        feat_2_text: "Il nostro algoritmo adatta la complessità dei testi e delle strutture grammaticali in tempo reale. Partendo da costrutti elementari, l'utente affronta un aumento progressivo delle difficoltà combinato con esercizi interattivi di digitazione ed espressione scritta, garantendo una memorizzazione a lungo termine.",
        feat_3_title: "Gamification e Progresso Sociale",
        feat_3_text: "L'apprendimento diventa un'esperienza collective stimolante. Monitora analiticamente i tuoi progressi quotidiani, confronta i tuoi traguardi linguistici all'interno di classifiche globali o private e condividi i tuoi successi con gli amici, aumentando la motivazione e la costanza nello studio giornaliero.",
        feat_4_title: "Approccio Flessibile e Personalizzato",
        feat_4_text: "Un sistema didattico estremamente duttile progettato sia per chi si avvicina a una nuova lingua da zero sia per chi vuole affinare le sfumature di una conversazione avanzata. È possibile configurare dinamicamente il carico di studio giornaliero in base al proprio stile di vita.",
        feat_5_title: "Canale Diretto e Feedback Interattivo",
        feat_5_text: "Partecipa attivamente all'evoluzione dell'ecosistema Polyglot Online. Offriamo un canale di comunicazione diretto e senza filtri con l'autore del progetto e il team di sviluppo, permettendoti di richiedere nuove lingue, proporre esercizi unici o vedere le tue idee prendere vita."
    },
    en: {
        nav_home: "Home",
        nav_languages: "Languages",
        nav_about_me: "About me",
        nav_login: "Login",
        nav_logout: "Logout",
        nav_welcome: "Hello, ",
        hero_title: "Learn your <br><span>favorite</span> language online",
        hero_subtitle: "An interactive eco-platform for learning foreign languages.",
        btn_choose: "Choose a language",
        about_title: "Behind the scenes of the wild world of linguistics.",
        about_text1: "The project was created by volunteers for a comfortable immersion into the culture of different countries.",
        about_subtitle: "How it works?",
        about_text2: "You choose a language card, log in, unlock interactive materials, and learn words with fun transition animations.",
        placeholder_map: "Map of the linguistic world",
        lang_title: "Our popular destinations",
        back_btn: "Back to languages",
        
        card_zh: "Chinese",
        card_es: "Spanish",
        card_en: "English",
        card_it: "Italian",
        card_ru: "Russian",
        card_ar: "Arabic",
        card_uk: "Ukrainian",
        card_pt: "Portuguese",
        card_de: "German",
        
        auth_title: "Login / Registration",
        auth_login_label: "Username:",
        auth_pass_label: "Password:",
        auth_placeholder_user: "Create or enter username",
        auth_placeholder_pass: "Enter password",
        auth_btn: "Continue",
        auth_success_reg: "Registration successful! Welcome, ",
        auth_success_login: "Welcome back, ",
        auth_error_pass: "Incorrect password!",
        
        desc_zh: "Welcome to the Chinese learning page. It is one of the oldest and most widely spoken languages in the world, based on a tonal system and hieroglyphic writing.",
        desc_es: "¡Hola! Spanish is the second most popular native language in the world. It is incredibly emotional, sonorous, and relatively easy for beginners to master.",
        desc_en: "Welcome! English is the main language of international communication, business, science, and technology.",
        desc_it: "Benvenuti! Italian is the language of great culture, the Renaissance, opera, and culinary arts. Almost all musical terms have Italian roots.",
        desc_ru: "Welcome! Russian is one of the world's major languages, famous for its rich literature, complex grammar, and wealth of expressive means.",
        desc_ar: "Ahlan wa sahlan! The Arabic language is written from right to left and has a unique root system for word construction.",
        desc_uk: "Welcome! The Ukrainian language is officially recognized as one of the most melodic in the world due to the unique alternation of vowels and consonants.",
        desc_pt: "Olá! Portuguese gave the world the culture of fado, samba, and capoeira. It is spoken not only in Portugal, but also in vast, sunny Brazil.",
        desc_de: "Guten Tag! German is the language of Kant, Goethe, and Einstein. It is known for its long compound words and strict word order.",

        home_features_title: "Our Exclusive Advantages",
        feat_1_title: "Visual Method & Total Immersion",
        feat_1_text: "A cutting-edge methodology based on the immediate association between native concepts and high-definition images. This completely eliminates the need for intermediate mental translation, accelerating the development of intuitive thinking directly in your target language from day one.",
        feat_2_title: "Step-by-Step Academic Progression",
        feat_2_text: "Our systematic approach ensures a smooth and gradual increase in lexical and grammatical difficulty. By integrating conceptual vocabulary with dynamic interactive typing tasks, the platform helps solidify theoretical language rules into effortless, automated long-term memory patterns.",
        feat_3_title: "Social Progression & Analytics",
        feat_3_text: "Language acquisition becomes an engaging and collective experience. Easily monitor your personal statistical growth, contrast and compare your linguistic accomplishments with your friends within competitive weekly leaderboards, and turn daily practice into an inspiring routine.",
        feat_4_title: "Adaptive & Custom Approach",
        feat_4_text: "An exceptionally versatile educational framework tailored to meet your individual requirements. Whether you are starting completely from scratch or looking to master advanced conversational nuance, you can dynamically configure your daily study load to match your lifestyle.",
        feat_5_title: "Direct Pipeline & Interactive Feedback",
        feat_5_text: "Become a crucial part of the ongoing Polyglot Online evolution. We provide a direct, unhindered communication channel with the project author and development team—allowing you to request new languages, contribute unique exercises, share constructive critiques, or see your ideas come to life."
    },
    ru: {
        nav_home: "Главная",
        nav_languages: "Языки",
        nav_about_me: "Обо мне",
        nav_login: "Войти",
        nav_logout: "Выйти",
        nav_welcome: "Привет, ",
        hero_title: "Изучай любимый <br><span>язык</span> онлайн",
        hero_subtitle: "Интерактивная эко-платформа для увлекательного изучения иностранных языков.",
        btn_choose: "Выбрать язык",
        about_title: "За кулисами удивительного мира лингвистики.",
        about_text1: "Проект создан волонтерами для комфортного и глубокого погружения в культуру различных стран.",
        about_subtitle: "Как это работает?",
        about_text2: "Вы выбираете карточку интересующего вас языка, проходите авторизацию, получаете полноценный доступ к интерактивным материалам и учите слова с помощью веселых анимаций переходов.",
        placeholder_map: "Карта лингвистического мира",
        lang_title: "Наши популярные направления",
        back_btn: "Назад к языкам",
        
        card_zh: "Китайский",
        card_es: "Испанский",
        card_en: "Английский",
        card_it: "Итальянский",
        card_ru: "Русский",
        card_ar: "Арабский",
        card_uk: "Украинский",
        card_pt: "Португальский",
        card_de: "Немецкий",
        
        auth_title: "Вход / Регистрация",
        auth_login_label: "Логин:",
        auth_pass_label: "Пароль:",
        auth_placeholder_user: "Создайте или введите логин",
        auth_placeholder_pass: "Введите пароль",
        auth_btn: "Продолжить",
        auth_success_reg: "Регистрация успешна! Добро пожаловать, ",
        auth_success_login: "С возвращением, ",
        auth_error_pass: "Неверный пароль!",
        
        desc_zh: "Добро пожаловать на страницу изучения китайского языка. Это один из самых древних и распространенных языков в мире, основанный на тональной системе и иероглифическом письме.",
        desc_es: "¡Hola! Испанский язык — второй по популярности родной язык в мире. Он невероятно эмоционален, звучен и относительно прост в освоении для новичков.",
        desc_en: "Welcome! Английский — главный язык международного общения, бизнеса, науки и технологий. Его знание открывает двери в любую точку земного шара.",
        desc_it: "Benvenuti! Итальянский — язык великой культуры, Ренессанса, оперы и кулинарии. Почти все музыкальные термины в мире имеют итальянские корни.",
        desc_ru: "Приветствуем! Русский язык — один из крупнейших языков мира, славящийся своей богатой литературой, сложной грамматикой и обилием выразительных средств.",
        desc_ar: "Ahlan wa sahlan! Арабский язык пишется справа налево и обладает уникальной корневой системой построения слов, а также завораживающей каллиграфией.",
        desc_uk: "Вітаємо! Украинский язык официально признан одним из самых певучих и мелодичных языков мира благодаря уникальному чередованию гласных и согласных звуков.",
        desc_pt: "Olá! Португальский язык подарил миру культуру фаду, самбы и капоэйры. На нем говорят не только в Португалии, но и в огромной солнечной Бразилии.",
        desc_de: "Guten Tag! Немецкий язык — это язык Канта, Гёте и Эйнштейна. Он известен своими длинными сложными словами и строгим фиксированным порядком слов.",

        home_features_title: "Наши Преимущества",
        feat_1_title: "Наглядный метод и глубокое погружение",
        feat_1_text: "Инновационная методика обучения, строящаяся на мгновенной ассоциации между новыми словами и яркими наглядными образами. Это исключает необходимость промежуточного мысленного перевода, ускоряя формирование интуитивного мышления прямо на изучаемом языке.",
        feat_2_title: "Постепенное академическое усложнение",
        feat_2_text: "Интеллектуальная система адаптации плавно повышает уровень сложности лексики и грамматики. Начиная с базовых конструкций, вы переходите к продвинутым темам, закрепляя правила с помощью интерактивных упражнений ввода и написания слов для надежной фиксации в долговременной памяти.",
        feat_3_title: "Социальный прогресс и геймификация",
        feat_3_text: "Изучение языков больше не будет рутиной. Наша платформа превращает учебный процесс в захватывающее приключение: детально отслеживайте личную статистику, соревнуйтесь в еженедельных лигах с друзьями и делитесь своими триумфами, поднимая мотивацию на максимум.",
        feat_4_title: "Гибкий и кастомизированный подход",
        feat_4_text: "Универсальная образовательная система, подстраивающаяся под любые индивидуальные цели. Неважно, начинаете ли вы учить язык с абсолютного нуля или оттачиваете нюансы продвинутой речи — вы всегда можете гибко настроить интенсивность занятий под свой ритм жизни.",
        feat_5_title: "Интерактивная связь с авторами проекта",
        feat_5_text: "Вы напрямую влияете на будущее развитие Polyglot Online. Мы открыли прозрачный канал связи с разработчиками: предлагайте новые языковые направления, присылайте уникальные упражнения, делитесь идеями и наблюдайте, как ваши предложения воплощаются в коде проекта."
    }
};